# Generated by Django 2.2.1 on 2019-06-17 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('team1', models.CharField(max_length=120)),
                ('team2', models.CharField(max_length=120)),
                ('tossWinner', models.CharField(max_length=120)),
                ('tossDecision', models.CharField(max_length=120)),
                ('result', models.CharField(max_length=120)),
                ('dlApplied', models.IntegerField()),
                ('winner', models.CharField(max_length=120)),
                ('winByRuns', models.IntegerField()),
                ('winByWickets', models.IntegerField()),
                ('playerOfTheMatch', models.CharField(max_length=120)),
                ('venue', models.CharField(max_length=120)),
                ('empire1', models.CharField(max_length=120)),
                ('empire2', models.CharField(max_length=120)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl.Seasons')),
            ],
        ),
    ]
