# Generated by Django 2.2.1 on 2019-06-17 06:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('team1', models.CharField(max_length=120)),
                ('team2', models.CharField(max_length=120)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('tossWinner', models.CharField(max_length=120)),
                ('tossDecision', models.CharField(max_length=120)),
                ('result', models.CharField(max_length=120)),
                ('dlApplied', models.IntegerField()),
                ('winner', models.CharField(max_length=120)),
                ('winByRuns', models.IntegerField()),
                ('winByWickets', models.IntegerField()),
                ('playerOfTheMatch', models.CharField(max_length=120)),
                ('venue', models.CharField(max_length=120)),
                ('empire1', models.CharField(max_length=120)),
                ('empire2', models.CharField(max_length=120)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl.Seasons')),
            ],
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.IntegerField()),
                ('battingTeam', models.CharField(max_length=120)),
                ('bowlingTeam', models.CharField(max_length=120)),
                ('over', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('batsman', models.CharField(max_length=120)),
                ('nonStriker', models.CharField(max_length=120)),
                ('bowler', models.CharField(max_length=120)),
                ('isSuperOver', models.IntegerField()),
                ('wideRuns', models.IntegerField()),
                ('byeRuns', models.IntegerField()),
                ('legbyeRuns', models.IntegerField()),
                ('noballRuns', models.IntegerField()),
                ('penaltyRuns', models.IntegerField()),
                ('batsmanRuns', models.IntegerField()),
                ('extraRuns', models.IntegerField()),
                ('totalRuns', models.IntegerField()),
                ('playerDismissed', models.CharField(max_length=120)),
                ('DismissalKind', models.CharField(max_length=120)),
                ('fielder', models.CharField(max_length=120)),
                ('matchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl.Matches')),
            ],
        ),
    ]
