# Generated by Django 2.2.1 on 2019-06-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasons',
            name='year',
            field=models.IntegerField(unique=True),
        ),
    ]
